name: pzl130
description: "aplikacja dla wÄ…skiego grona do nauki"
publish_to: 'none'

version: 1.0.1+6

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.9.1
  url_launcher: ^6.1.10
  file_picker: ^8.0.0
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  http: ^1.4.0
  webview_flutter: ^4.0.7
  syncfusion_flutter_pdfviewer: 31.1.19
  html: ^0.15.0
  flutter_pdfview: ^1.3.2
  path_provider: ^2.1.2
  flutter_svg: ^2.0.7
  flame: ^1.10.0
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.0.0
  local_auth: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/aircraft_bg.jpg
    - assets/pinup_girl.png
    - assets/cockpit/cockpit.svg
    - assets/images/orlik.png
    - assets/images/shahed.png
    - assets/images/bullet.png
    - assets/images/power_extra_bullet.png
    - assets/images/power_fast_fire.png
    - assets/images/power_life.png
    - assets/images/bryza.png


fonts:
  - family: Orbitron
    fonts:
      - asset: assets/fonts/Orbitron-Regular.ttf
      - asset: assets/fonts/Orbitron-Bold.ttf
        weight: 700

  - family: RobotoCondensed
    fonts:
      - asset: assets/fonts/RobotoCondensed-Regular.ttf
      - asset: assets/fonts/RobotoCondensed-Bold.ttf
        weight: 700
